name: Submit Expo App

on:
  workflow_dispatch:

jobs:
  submit:
    runs-on: macos-latest
    strategy:
      matrix:
        node: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn      
          cache-dependency-path: ${{ github.workspace }}/alloha

      - name: 📦 Install dependencies
        run: yarn
        working-directory: ${{ github.workspace }}/alloha

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: aloha-2024-05-27
          path: ${{ github.workspace }}/alloha/app-build

      - name: Submit to Expo
        run: npx expo submit --path ${{ github.workspace }}/alloha/app-build/aloha-2024-05-27
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
